### ISSUE TITLE
IRC Nicknames aren't showing up properly

### ISSUE THREAD

**Issue by chex3** [insomniacslk/irc-slack#11]
The nickname, or username of the person chatting on each slack channel is not working properly. 

In most cases, it is just sending a "U#######" string for each person, altho it does occasionally send a person's username: 

> 10:34 < U9X9H2KPG> post/notice/message
> 15:14 < U5WQ1RXLL> That's me in the middle
> 15:15 < moxuz> the octopus?

I assume this is a Slack internal ID being sent out. 

This is the number one bug/issue for me, makes chatting in the Slack channels almost useless, if I cant hilite people back in response in IRSSI. 

Thanks!!

-- Stefan S

**Comment by insomniacslk** [comment]
hey Stefan,

thanks for reporting! This should only happen when new people join the team, or if something goes wrong when fetching the user list upon the first connection, but it should be an easy fix. The first is basically https://github.com/insomniacslk/irc-slack/issues/3 . The latter, I've never seen in practice.

Can you verify if this issue appears only with newly joined people?

Thanks

**Comment by insomniacslk** [comment]
I can't reproduce locally, but I had a feeling about what it could be. @chex3 mind to test it with this patch? https://github.com/insomniacslk/irc-slack/compare/nick_join_part

**Comment by insomniacslk** [comment]
I could reproduce the error. This happens on larger Slack channels/teams. Slack started truncating the list of members as of December 2017, https://api.slack.com/changelog/2017-10-members-array-truncating . Currently the list is capped at 500 members, so only 500 people per channel will be resolved from ID to name.

The solution is to use `conversation.members` instead. I will work on a fix in the next days

**Comment by insomniacslk** [comment]
I fixed the issue on my side but this also needs fixing in the underlying slack library as pointed out in the above PR

**Comment by insomniacslk** [comment]
I also need to port that code for groups, and refactor and clean it up

**Comment by pdellaert** [comment]
hi @insomniacslk , i noticed this issue still popping up, but in a somewhat different behaviour: I have a Slack environment where i'm part of 40 channels. And for the last 10 channels or so, it starts showing all the usernames as these `U...` nicknames. 

However, when they type a message, i do see their proper handle.
Also, in our mandatory general channel, all users show up correctly, so it is able to fetch larger numbers of users (there's 450 users on that).

Example of such a channel:
```
19:17:25 [Users #unique_constraints]
19:17:25 [ pdellaert] [ U09CVRLAJ] [ U0G8NFSUT] [ U22A0V50S] [ UE39T0HQQ]
19:17:25 [ U02TFCBT4] [ U0A2TAARJ] [ U0KNMA9J8] [ U2ASEM5FD]
19:17:25 [ U03CE7MSM] [ U0CUBPBBM] [ U0TGZQ1E2] [ U6Y42SF71]
19:17:25 -!- Irssi: #unique_constraints: Total of 13 nicks [0 ops, 0 halfops, 0 voices, 13 normal]
20:32:49 [Users #unique_constraints]
20:32:49 [ pdellaert] [ U09CVRLAJ] [ U0G8NFSUT] [ U22A0V50S] [ UE39T0HQQ]
20:32:49 [ U02TFCBT4] [ U0A2TAARJ] [ U0KNMA9J8] [ U2ASEM5FD]
20:32:49 [ U03CE7MSM] [ U0CUBPBBM] [ U0TGZQ1E2] [ U6Y42SF71]
```
(Initial is join, second is a `/n` in irssi)
